version: '3.8'
networks:
    app-tier:
        driver: bridge
services:
  php:
    container_name: php_server
    build:
      context: ./server
      dockerfile: docker/php/Dockerfile
    networks:
      - app-tier
    ports:
      - "9091:91"
    volumes:
      - ./server:/srv/app
  nginx:
    container_name: php_server_nginx
    build:
      context: ./server
      dockerfile: docker/nginx/Dockerfile
    networks:
      - app-tier
    ports:
      - "8000:80"
    volumes:
      - ./server/public:/srv/app/public
    depends_on:
      - php
  ubuntu:
    container_name: ubuntu_server
    build: ./client
    networks:
      - app-tier
    ports:
      - "9092:92"
    restart: on-failure
    command: ["sleep","infinity"]
    volumes:
      - ./client/python:/home/client/python